version: '3'

services:
    vnc:
        image: shiftinv/wine:vnc
        restart: 'no'
        environment:
            # VNCPASSWD: '<unset>'
            VNCRESOLUTION: '1920x1080'
        ports:
            - '127.0.0.1:5901:5901'
