FROM shiftinv/wine-vnc:latest

USER root
RUN $APT_CMD update \
 && $APT_CMD install -y xvfb \
 && apt-get clean \
 && find /var/lib/apt/lists/ /tmp/ /var/tmp/ -mindepth 1 -maxdepth 1 -exec rm -rf "{}" +
USER user

ARG DOTNET_VERSION
RUN [ -n "$DOTNET_VERSION" ] || { echo "\$DOTNET_VERSION is not set" >&2; exit 1; }
RUN export DISPLAY=:0 \
 && (Xvfb ${DISPLAY} &) \
 && winetricks -q --verify dotnet${DOTNET_VERSION} \
 && rm -rf ~/.cache/winetricks
