#!/bin/bash -xe

DOCKER_ARGS=(
    -f "$DOCKERFILE_PATH"
)
for tag in ${DOCKER_TAG//,/ }; do
    if [[ ! "$tag" =~ ^(.*-)?vnc$ ]]; then
        echo "Invalid tag: $tag" >&2
        exit 1
    fi

    DOCKER_ARGS+=(-t "$DOCKER_REPO:$tag")
    [[ "$tag" =~ ^(.*)-vnc$ ]] && DOCKER_ARGS+=(--build-arg "BASE_IMAGE=$DOCKER_REPO:${BASH_REMATCH[1]}")
done

docker build "${DOCKER_ARGS[@]}" .
